apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: maps-by-org-name
  labels:
    name: maps-by-org-name
  namespace: apigee
spec:
  replicas: 1
  selector:
    matchLabels:
      component: maps-by-org-name
  template:
    metadata:
      labels:
        component: maps-by-org-name
        routable: "true"
      annotations:
        privateHosts: sso.k8s.local
        privatePaths: 3000:/maps-by-org-name
    spec:
      containers:
      - name: maps-by-org-name
        image: maps-by-org-name
        imagePullPolicy: IfNotPresent
        env:
          - name: PORT
            value: "3000"
          - name: SHIPYARD_PRIVATE_SECRET
            valueFrom:
              secretKeyRef:
                name: routing
                key: private-api-key
          - name: SPEEDUP
            value: "10" 
          - name: INTERNAL_SY_ROUTER_HOST
            valueFrom:
              fieldRef:
                fieldPath: status.podIP          
          - name: INTERNAL_SY_ROUTER_PORT
            value: "30556"
          - name: IPADDRESS
            valueFrom:
              fieldRef:
                fieldPath: status.podIP          
        ports:
          - containerPort: 3000